version: '3'

services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: claudiu
      MONGODB_INITDB_ROOT_PASSWORD: secret
      MONGODB_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-pw 